#!/bin/sh

rand=$(
while read p; do
	status=$(echo $p | awk '{print $4}')
	isEmpty=$(echo $p | awk '{print $5}')
	if [ "$status" == "start" ] && [ ! -z "$isEmpty" ]
	then
		echo "$p" | awk '{$1=$2=$3=$4=""; $0=$0} NF=NF'
	fi
done <logs/2020-03 | uniq | dmenu
)

echo $rand
