#! /bin/bash

args=("$@")
currentDir=$( 
cd $(dirname "$0") 
pwd)
file=$currentDir/logs/$(date "+%Y-%m")
log=$(date "+%u %d %H:%M:%S")

convertsecs() {
 ((h=${1}/3600))
 ((m=(${1}%3600)/60))
 ((s=${1}%60))
 printf "%02d:%02d:%02d\n" $h $m $s
}

# if file don't exist create one
if [ "$1" == "+" ] && [ ! -f "$file" ]
then
proj=$(
while read p; do
	if [ "$(echo $p | awk '{print $4}')" == "start" ] && [ ! -z "$(echo $p | awk '{print $5}')" ]
	then
		echo "$p" | awk '{$1=$2=$3=$4=""; $0=$0} NF=NF'
	fi
done <$file | uniq | dmenu)
	echo $log start $proj >> $file
	echo "TimeTRK started."
	exit 1
fi

# get the last status if file exist
if [ -f "$file"  ]
then
	status=$(tail -n 1 $file | awk '{print $4}')
fi

# trk start if last status is stop
if [ "$1" == "+" ] && [ "$status" == "stop" ]
then
proj=$(
while read p; do
	if [ "$(echo $p | awk '{print $4}')" == "start" ] && [ ! -z "$(echo $p | awk '{print $5}')" ]
	then
		echo "$p" | awk '{$1=$2=$3=$4=""; $0=$0} NF=NF'
	fi
done <$file | uniq | dmenu)
	echo $log start $proj >> $file
	echo "TimeTRK started."
	exit 1
fi

# trk start won't start if already running
if [ "$1" == "+" ] && [ "$status" == "start" ]
then
	echo "Already running."
	exit 1
fi

# trk stop if last status is start
if [ "$1" == "-" ] && [ "$status" == "start" ]
then
	startingTime=$(date -d"$(tail -n 1 $file | awk '{print $3}')" +%s)
	now=$(date -d"$(date "+%H:%M:%S")" +%s)
	elapsedTime=$(($now-$startingTime))
	echo $log stop $(convertsecs $elapsedTime) >> $file
	echo "TimeTRK stopped."
	exit 1
fi

# trk stop won't stopl if nothing is running
if [ "$1" == "-" ] && [ "$status" == "stop" ]
then
	echo "No running tracker."
	exit 1
fi

# show the current tracking 
if [ "$1" == "" ] && [ "$status" == "start" ]
then
	startingTime=$(date -d"$(tail -n 1 $file | awk '{print $3}')" +%s)
	now=$(date -d"$(date "+%H:%M:%S")" +%s)
	elapsedTime=$(($now-$startingTime))
	echo $(convertsecs $elapsedTime)
	exit 1
fi

# if nothin is running show 00:00:00
if [ "$1" == "" ] && [ "$status" == "stop" ]
then
	echo 00:00:00
fi

# trk reporting 
if [ "$1" == "report" ]
then
	selectFile=$currentDir/logs/$(ls $currentDir/logs | dmenu)
	sum=0

	var=$(
		while read p; do
			echo "$p" | awk '{print $2}'
		done <$selectFile | uniq
	)

	while read p; do
		dailyTime=0
		while read i; do
			if [ "$(echo $i | awk '{print $2}')" == "$p" ] && [ "$(echo $i | awk '{print $4}')" == "stop" ]
			then
				time=$(echo "$i" | awk '{print $5}')
				dayOfTheWeek=$(echo "$i" | awk '{print $1}')
				day=$(echo "$i" | awk '{print $2}')
				timeInSec=$(($(date -d"$time" +%s) - $(date -d"00:00:00" +%s) ))
				sum=$(($sum + $timeInSec))
				dailyTime=$(($dailyTime + $timeInSec))
			fi
		done <$selectFile
		echo "$p":	$(convertsecs "$dailyTime")
	done <<< "$var"

	echo ================
	echo Summary:	$(convertsecs $sum)
fi
